name: Build Tauri App for Linux

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rust-src, rustfmt, clippy
        
    # Install Linux dependencies needed for Tauri
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          desktop-file-utils
        
    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm' # Change to 'npm' or 'yarn' if needed
        
    # Install package manager (change to npm or yarn if needed)
    - name: Install pnpm
      run: npm install -g pnpm
      
    # Install project dependencies
    - name: Install project dependencies
      run: pnpm install
      
    # Build the frontend (if using a framework like Vue/React/Svelte)
    - name: Build frontend
      run: pnpm run build
      
    # Build Tauri app for multiple Linux targets
    - name: Build Tauri application
      run: |
        pnpm tauri build --target deb
        pnpm tauri build --target appimage
        pnpm tauri build --target rpm
        
    # Upload artifacts for all build targets
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-builds
        path: |
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/appimage/*.AppImage
          src-tauri/target/release/bundle/rpm/*.rpm
          
    # Optional: Create GitHub release (only on main branch pushes)
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        name: "v${{ github.run_number }} Linux Build"
        body: "Automated Linux builds for Tauri app"
        draft: false
        prerelease: false
        files: |
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/appimage/*.AppImage
          src-tauri/target/release/bundle/rpm/*.rpm
