name: Build Tauri App for Linux

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rust-src, rustfmt, clippy
        
    - name: Install system dependencies
      run: |
        sudo add-apt-repository -y universe
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libjavascriptcoregtk-4.0-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          desktop-file-utils \
          libsoup2.4-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      run: npm install -g pnpm
        
    - name: Install project dependencies
      run: pnpm install
      
    # Only include if your project has a build script
    # - name: Build frontend
    #   run: pnpm run build
      
    - name: Build Tauri application
      run: |
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
        pnpm tauri build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-builds
        path: src-tauri/target/release/bundle
