name: Build Tauri App for Linux

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04  # Explicitly use Ubuntu 24.04
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rust-src, rustfmt, clippy
        
    # Install Linux dependencies needed for Tauri (updated for Ubuntu 24.04)
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \  # Changed from 4.0 to 4.1
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          desktop-file-utils \
          libayatana-appindicator3-dev  # Additional dependency for Ubuntu 24.04
        
    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm' # Change to 'npm' or 'yarn' if needed
        
    # Install package manager
    - name: Install pnpm
      run: npm install -g pnpm
      
    # Install project dependencies
    - name: Install project dependencies
      run: pnpm install
      
    # Build the frontend
    - name: Build frontend
      run: pnpm run build
      
    # Build Tauri app for multiple Linux targets
    - name: Build Tauri application
      run: |
        pnpm tauri build --target deb
        pnpm tauri build --target appimage
        # pnpm tauri build --target rpm  # RPM might need additional setup
        
    # Upload artifacts for all build targets
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-builds
        path: |
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/appimage/*.AppImage
          # src-tauri/target/release/bundle/rpm/*.rpm
